### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by DabirSA** [geekbozu/EliteDangerousMatricBridge#1]
When I try to run the program, nothing happens at all.

**Comment by geekbozu** [comment]
lets start simple, 
Did you install net5.0? That is a pre-requisite and I am not 100% on if it will alert you that you are missing it when double clicking the executable.

**Comment by DabirSA** [comment]
I thought I had .Net 5.0 installed, but it turns out I didn't. There was no alert, it just failed to show anything. It seems to be working now.

**Comment by geekbozu** [comment]
Yeah if you do not run it through  a command line it will just flash that its missing and go away...kinda dumb but out of my control.
